### ISSUE TITLE
`npm start` won't run

### ISSUE THREAD

**Issue by greenbech** [fnky/particle-life#1]
It seems like there is a dependency missing—`canvas-sketch-cli`. I guess you have that installed that globally. I think you either should say that the user has to download that globally in the README or add `"canvas-sketch-cli"`as a dependency in `package.json`. I am not completely sure what's best, but I think the latter is the best practice 😄

**Comment by fnky** [comment]
You're right, I used it from a global install. I'll add it as a dev dependency.
