### ISSUE TITLE
Compiling in Linux, not really an issue just info

### ISSUE THREAD

**Issue by doggodanubus** [fnky/particle-life#6]
Without a massive overkill of autoconf or cmake just find and install the ENTIRE
SMFL library. In Fedora it's capital sensitive so look for SMFL and SMFL-devel. Once those are installed and your SURE they are installed then for 64bit Fedora try this as a shell script
Since I don't have a 32bit system handy you may be able to run this as is or remove the 64 bit reference. SFML is butt sniffing slow and while it seems easy to use it is highly meh. 

```
`#!/bin/bash
g++ -I/usr/include -I/usr/include/SFML -L/usr/lib -L/usr/lib64  Main.cpp Universe.cpp -o particlelife  -lsfml-graphics -lsfml-audio -lsfml-window -lsfml-network -lsfml-system`
```

Try the javascript version perhaps? It allows on the fly settings and it runs in a browser from the below link, go one up to get the code so you can use it elsewhere. It is very much faster or seems to be.

https://fnky.github.io/particle-life

**Comment by fnky** [comment]
This repository is only an unofficial port of the [original project](https://github.com/HackerPoet/Particle-Life) by HackerPoet. I suggest you create a pull request to add this information there instead.
